from selenium.webdriver import Chrome
from selenium import webdriver
from selenium.webdriver.common.by import By

#Base information used to gather flight data
startAirPort = "Detroit"
endAirPort = "Zurich"
startDate = "January 24th"
endDate = "January 31st"


def genFlightList(startAirPort, endAirPort, startDate, endDate):
    #Generates the necessary information to setup the google search
    google_query = "Flights " + startAirPort + " to " + endAirPort + " from " + startDate + " to " + endDate

    #print(google_query)

    #adds in the main google URL info
    google_query = google_query.replace(" ", "+")
    main_URL = "https://google.com/search?q=" + google_query

    #sets up the selenium web driver
    driver = webdriver.Chrome(executable_path = r"/Users/rohitchakravarty/Documents/PersonalProjects/PythonPrograms/TripPlanner/chromedriver")
    driver.get(main_URL)

    #Grabs the table generated by google with flight data from the given dates & locations
    origin = driver.find_element_by_xpath("/html/body/div[8]/div[3]/div[10]/div[1]/div[2]/div/div[2]/div[2]/div/div/div[1]/div/div/div/div[2]")

    
    #Converts the raw text into a dictionary that is easier to read
    lineList = origin.text.splitlines()
    PlaneInfo = {}
    #Processing necessary to make the scraped data more readable
    for x in range (len(lineList)):
        if("Nonstop" in lineList[x] or "Connecting" in lineList[x]):
            lineList[x+1] = lineList[x+1][5:] + "+"
            PlaneInfo[lineList[x]] = lineList[x+1]

    driver.close()

    print("Plane Info Complete")
    return PlaneInfo



#allPlaneInfo = genFlightList(startAirPort, endAirPort, startDate, endDate)
#print(allPlaneInfo)
